### ISSUE TITLE
Where are the goddam dragons?

### ISSUE THREAD

**Issue by Garueri** [AllTheMods/atm6-sky#226]
I'm trying to do the OP althemodium paxel, but I can't  find the tier 4-5 female dragons to kill, get an egg, and tame
And oh my god, it's so expensive to do the  dragon forges it hurts me
If you also are looking for a way to kill the dragons, I think they are buffed or something, but the only means to kill one that I know is using the ''morgan'' from mahou tsukai and buff it killing many villagers

**Comment by Vertigo81** [comment]
I haven't found any female ones yet (I've scoured pretty widely, few thousand chunks, no luck).  But I managed to find 5 or 6 males on the surface.

I killed one, took using an unobtanium sword from tinkers, a lot of allthemodium carrots, and still died like 10 times to wear down it's 30,000 health.  I'm not sure what attack was killing me exactly, but it was ice based judging from the death message.

I'd be doing fine, lot of damage but manageable with healing if I pulled back.  But every once in a while it would just insta kill me >_<. Very frustrating.  Haven't found frost damage protection yet, and the thousands of armour and magic armour from unobtainable armour doesn't seem to help much.

After that first mess I started capturing them instead.  Hoping I can rig up some kind of auto killer.  Also hoping that cloning them might net some females for eggs?  Because seriously can't find any.

**Comment by BlindedShooter** [comment]
You need to upgrade ATM6 sky to 1.0.6b, which was released 3 days ago.

**Comment by Vertigo81** [comment]
Don't know about the OP, but I did when it came out.  Before that there were No dragons.  Now I can only find the males.

**Comment by Garueri** [comment]
> You need to upgrade ATM6 sky to 1.0.6b, which was released 3 days ago.

Indeed, I was hunting dragon before the patch came out, and now I can see dragons on the surface, don't know about females though

**Comment by Garueri** [comment]
Well Honestly I gave up, I just did a paxel from silent gear with efficiency IX and the  Morgan from mahou tsukai, the paxel instamines anything and the Morgan deals scalable damage, I currently have 35K damage/hit and instamine, so what is the reason to pursue the allthemodium paxel?
The only reason I can see why is to do better armor using the unobtanium-vibranium ingot with the ice dragon, but honestly, the only reason to do so would be protection against dragons, but If you are not going to hunt dragons anymore, why would you do it anyway

**Comment by Garueri** [comment]
> I haven't found any female ones yet (I've scoured pretty widely, few thousand chunks, no luck). But I managed to find 5 or 6 males on the surface.
> 
> I killed one, took using an unobtanium sword from tinkers, a lot of allthemodium carrots, and still died like 10 times to wear down it's 30,000 health. I'm not sure what attack was killing me exactly, but it was ice based judging from the death message.
> 
> I'd be doing fine, lot of damage but manageable with healing if I pulled back. But every once in a while it would just insta kill me >_<. Very frustrating. Haven't found frost damage protection yet, and the thousands of armour and magic armour from unobtainable armour doesn't seem to help much.
> 
> After that first mess I started capturing them instead. Hoping I can rig up some kind of auto killer. Also hoping that cloning them might net some females for eggs? Because seriously can't find any.

The instakill attack is a particle they throw at you, ice is the worst because it also slows you down, I'd recommend giving up on dragons and moving to something more useful, as I just listed, there are better options to the allthemodium alloys, beyond that having a dragon has probably no benefit
