### ISSUE TITLE
Ingots and Blocks

### ISSUE THREAD

**Issue by MikeThunder308** [AllTheMods/atm6-sky#357]
I prefer to have all the Ingots and Blocks from different mods separated. Like Mekanism's ingots and Immersive Engineering Ingots and Blocks separate. How do I do this. I've took out the mod, All The Ores, but that creates errors and only gives one ingot, like Copper Ingot from Mekanism, but not several Ingots.

**Comment by MikeThunder308** [comment]
The mod, AllTheOres, unifies all the ingots does it not, or am I looking at the wrong mod?

**Comment by MikeThunder308** [comment]
Yes, but the only Ingots I get are from that mod.

**Comment by Mightylight** [comment]
yeah, like i said. Make the oredictionificator from mekanism. That can turn AllTheOres ingots into others if you so please

**Comment by MikeThunder308** [comment]
How would I do that?

**Comment by MikeThunder308** [comment]
I went into creative and got the ingots, the ingots there were all separated but on the jei it only gives the one ingot.

**Comment by Mightylight** [comment]
???? what was the point of asking when you are not gonna do anything with the tips i give you?

**Comment by DrMrPotatoe** [comment]
ok mike, if u want to get the ingot from another mod, all be it they would have the same uses as the AllTheOres ingots, you can make a machine called the oredicttionator, as myghtilight commented, and change them, using their tags, to the desired ones.
all the ingots are unified because otherwise, you would need to get the same ingot through several routes, each one to do the same thing.

**Comment by MikeThunder308** [comment]
Sorry, I was trying to work out how to use and also get the tags for each ingot. So I went into creative to get the tags, thats when I found that all the Ingots are there.

**Comment by Mightylight** [comment]
if you fixed your issue, you may close this. Have a good day
