### ISSUE TITLE
Lost world

### ISSUE THREAD

**Issue by ironryan91f** [AllTheMods/atm6-sky#473]
So after spending idk how many hours playing, i was going thru and checking off tasks that i have done over then out of no where my world was reset, i lost ever thing i  had built, so i force closed it without saving hoping that i might bring me back to my last server save and that id only lose maybe a couple hours at most but no it was still gone. Is there any way that id beable to get my world back or do i have to start all over again

**Comment by levishores** [comment]
For the record, I just had this happen to me - it was associated with the introductory quest tasks which describe the various /skyblock create commands. Why this quest task TRIGGERED this command is beyond me? I got taken to a new skyblock instance, but realized what happened - I did ‘/skyblock leave’, and got back to my island, but now all the stuff in my inventory is gone. Wish I knew how to get it back; the island that was created is still there (by ‘team name’ it seems via /skyblock list … I presume my inventory is in there, but I can’t get back to it because I left the team)… anyone have any suggestions?

**Comment by oly2o6** [comment]
those quests are to create your island, the issue was you built your base in spawn, not on "your island" so levishores, your items wouldve despawned at spawn, and ironryan, your base is at spawn, the world did not reset (also yes im over a month late, and most likely too late)
