### ISSUE TITLE
Are there any tools that might help to detect performance issues with Compact Machines / Crafter / Xnet?

### ISSUE THREAD

**Issue by AnLyze** [AllTheMods/atm6-sky#516]
I got lag spikes / everytime i'm inside my compact machines. It took 5 - 10 seconds inside to freeze for 5 - 10 seconds. The lag spike still happening even when i'm going outside the Compact Machines for every 10 - 20 seconds with freeze time of 5 - 10 seconds. I didn't have any consistent lag spikes before so i tried to troubleshooting by lower the Xnet extract rate and disable the crafter input. But still didn't find any clues what to do. I think i got this lag when i got vibranium ore piece and allthemodium ore pieces. I tried to look the consoles and it only says server can't keep up.  Any tools to detect these problem? Thanks.

**Screenshot**
![Screenshot](https://imgur.com/aaYzFF9.png)

**What inside Compact Machines**
- 5 Auto Sieves with Netherite Mesh
- 8 Auto Hammer
- 4 Pedestal Generator (1 Endstone 1 Netherack 2 Cobblestone)
- 1 Obisidan Crate (for buffering sieve loot)
- 2 Crafter Tier 3 (for compacting ore piece into ore chunk)
- 1 Drawer Controller
- 12 2x2 Oak Drawer with Emerald Upgrade and Void Upgrade
- 1 Cyclic Battery
- 1 Flux Point

**Comment by 19175** [comment]
First thing you can look at is pressing `Shift +F3`, this will show a pi chart with what is using the most of Minecrafts performance. You can then use number row keys to narrow in and expand each section of the pi chart. (there will be a list with names next to the various numbers for what each key will expand, but 1 will always expand the highest one, and 9 the 9th highest ect)

If you want a static list that isn't constantly moving you can use spark to profile what is causing lag, run `/spark profiler` while inside the machine, wait ~10 secs then run `/spark profiler --stop` (if you are on a server run these commands with `/sparkc` instead of `/spark` so that you profile your client and not the server)
That will give you a link in chat, click it and it will take you to your results. By expanding the various drop downs it will show u what is causing the lag, sorted by highest use first. If you are playing on single player the first few drop downs will be related to server tick time, not fps lag, so make sure to check that.

If you happen to find a block is causing lag through either of the above methods, but cannot locate it, you can use `/tellme locate` to locate a specific block in currently loaded chunks. More info on that is in one of the first-page quests.

**Comment by oly2o6** [comment]
adding observable next update. should help
