### ISSUE TITLE
Problem With Recipes

### ISSUE THREAD

**Issue by XiNaru** [AllTheMods/atm6-sky#556]
I wanted to report that I am not seeing some recipes on Industrial Forgoing.

For example the Simple and Advanced Machinecases.

I can't craft the laser drill that way.

**Comment by badgittiger** [comment]
The Dissolution chamber should have these recipes. The simple, advanced and supreme recipes are missing from JEI, as are the range/speed/efficiency upgrade recipes

**Comment by XiNaru** [comment]
honestly i wouldn't write it here if it weren't for that.

I press the button to show the recipe .... NOTHING comes.

Right-click (show usage) on the chamber in the Jei ONLY shows the recipe for pink slime balls. there is nothing more.

**Comment by Rat-bags** [comment]
yeh i have just been told about this on my server to, and people are not happy with bad update after bad update and I get the hate please ATM team have this stuff tested b4 setting as release there beta tags for a reason

**Comment by notFalkon** [comment]
Downgrade jei (the standalone mod) from `1.16.5-7.7.1.121` to `1.16.5-7.7.1.118`

**Comment by Rat-bags** [comment]
notFalkon Thank u so much that worked now telling other how to do that has them going erm how.. can't win lmao

**Comment by oly2o6** [comment]
Thank you for the feedback and the fix, i would just like to note although we wish we could, testing every little thing is literally impossible, we test anything we can think of, have testers too, but sometimes stuff just falls through the cracks, especially with tens of thousands of recipes JEI is one of those things that you can never actually test, will have it fixed in the next version, last update was a big one so this one will be mostly a cleanup with a few new things
